export const fakeMaterialsData = [
    {
        itemId: 1,
        itemNo: "item 311",
        description: "Concrete Mix - 4000 psi",
        quantity: 100,
        unit: "cu.m",
        testsRequired: 5,
        testsOnFile: 3,
        balance: 2,
        status: "Pending",
    },
    {
        itemId: 2,
        itemNo: "item 312",
        description: "Rebar - 16mm",
        quantity: 200,
        unit: "pcs",
        testsRequired: 4,
        testsOnFile: 4,
        balance: 0,
        status: "Completed",
    },
    {
        itemId: 3,
        itemNo: "item 313",
        description: "Cement Bags",
        quantity: 50,
        unit: "bags",
        testsRequired: 3,
        testsOnFile: 2,
        balance: 1,
        status: "Ongoing",
    },
    {
        itemId: 4,
        itemNo: "item 314",
        description: "Gravel - 3/4 inch",
        quantity: 500,
        unit: "cu.m",
        testsRequired: 6,
        testsOnFile: 4,
        balance: 2,
        status: "Ongoing",
    },
    {
        itemId: 5,
        itemNo: "item 315",
        description: "Sand - Fine Aggregate",
        quantity: 300,
        unit: "cu.m",
        testsRequired: 5,
        testsOnFile: 3,
        balance: 2,
        status: "Pending",
    },
    {
        itemId: 6,
        itemNo: "item 316",
        description: "Steel Plate - 10mm",
        quantity: 100,
        unit: "pcs",
        testsRequired: 4,
        testsOnFile: 4,
        balance: 0,
        status: "Completed",
    },
    {
        itemId: 7,
        itemNo: "item 317",
        description: "Plywood - Marine",
        quantity: 200,
        unit: "sheets",
        testsRequired: 3,
        testsOnFile: 3,
        balance: 0,
        status: "Completed",
    },
    {
        itemId: 8,
        itemNo: "item 318",
        description: "Anchor Bolts - 20mm",
        quantity: 150,
        unit: "sets",
        testsRequired: 4,
        testsOnFile: 2,
        balance: 2,
        status: "Ongoing",
    },
    {
        itemId: 9,
        itemNo: "item 319",
        description: "Epoxy Resin",
        quantity: 80,
        unit: "liters",
        testsRequired: 5,
        testsOnFile: 4,
        balance: 1,
        status: "Pending",
    },
    {
        itemId: 10,
        itemNo: "item 320",
        description: "PVC Pipes - 100mm",
        quantity: 250,
        unit: "pcs",
        testsRequired: 3,
        testsOnFile: 3,
        balance: 0,
        status: "Completed",
    },
    {
        itemId: 11,
        itemNo: "item 321",
        description: "Paint - White",
        quantity: 60,
        unit: "gallons",
        testsRequired: 2,
        testsOnFile: 1,
        balance: 1,
        status: "Pending",
    },
    {
        itemId: 12,
        itemNo: "item 322",
        description: "Electrical Wire - 5mm",
        quantity: 400,
        unit: "meters",
        testsRequired: 3,
        testsOnFile: 3,
        balance: 0,
        status: "Completed",
    },
    {
        itemId: 13,
        itemNo: "item 323",
        description: "Aluminum Sheet - 2mm",
        quantity: 100,
        unit: "sheets",
        testsRequired: 4,
        testsOnFile: 2,
        balance: 2,
        status: "Ongoing",
    },
];
