export const fakeMaterialsData = [
    {
        itemId: 1,
        itemNo: "item 311",
        description: "Concrete Mix - 4000 psi",
        materials: [
            {
                id: 101,
                name: "Concrete",
                testRequired: "Compressive Strength Test",
                unit: "cu.m",
                testsOnFile: 0,
                balance: 2,
                quantity: 50,
            },
            {
                id: 102,
                name: "Cement",
                testRequired: "Fineness Test",
                unit: "bags",
                testsOnFile: 1,
                balance: 1,
                quantity: 20,
            },
            {
                id: 103,
                name: "Gravel",
                testRequired: "Sieve Analysis",
                unit: "cu.m",
                testsOnFile: 1,
                balance: 0,
                quantity: 30,
            },
            {
                id: 104,
                name: "Sand",
                testRequired: "Moisture Content Test",
                unit: "cu.m",
                testsOnFile: 1,
                balance: 1,
                quantity: 40,
            },
            {
                id: 105,
                name: "Water",
                testRequired: "Water-Cement Ratio Test",
                unit: "liters",
                testsOnFile: 1,
                balance: 0,
                quantity: 5000,
            },
        ],
        quantity: 100,
        unit: "cu.m",
        testsRequired: "Slump Test",

        testsOnFile: 0,
        balance: 2,
    },
    {
        itemId: 2,
        itemNo: "item 312",
        description: "Rebar - 16mm",
        materials: [
            {
                id: 201,
                name: "Steel",
                testRequired: "Tensile Strength Test",
                unit: "pcs",
                testsOnFile: 2,
                balance: 2,
                quantity: 100,
            },
            {
                id: 202,
                name: "Iron",
                testRequired: "Chemical Composition Test",
                unit: "pcs",
                testsOnFile: 1,
                balance: 1,
                quantity: 50,
            },
            {
                id: 203,
                name: "Carbon",
                testRequired: "Bend Test",
                unit: "pcs",
                testsOnFile: 1,
                balance: 0,
                quantity: 30,
            },
        ],
        quantity: 200,
        unit: "pcs",
        testsRequired: "Tensile Strength Test",

        testsOnFile: 4,
        balance: 0,
    },
    {
        itemId: 3,
        itemNo: "item 313",
        description: "Cement Bags",
        materials: [
            {
                id: 301,
                name: "Cement",
                testRequired: "Setting Time Test",
                unit: "bags",
                testsOnFile: 1,
                balance: 1,
                quantity: 50,
            },
            {
                id: 302,
                name: "Limestone",
                testRequired: "Fineness Test",
                unit: "bags",
                testsOnFile: 0,
                balance: 0,
                quantity: 25,
            },
            {
                id: 303,
                name: "Clay",
                testRequired: "Soundness Test",
                unit: "bags",
                testsOnFile: 1,
                balance: 0,
                quantity: 20,
            },
            {
                id: 304,
                name: "Gypsum",
                testRequired: "Moisture Content Test",
                unit: "bags",
                testsOnFile: 0,
                balance: 0,
                quantity: 15,
            },
        ],
        quantity: 50,
        unit: "bags",
        testsRequired: "Fineness Test",
        testsOnFile: 2,
        balance: 1,
    },
    {
        itemId: 4,
        itemNo: "item 314",
        description: "Gravel - 3/4 inch",
        materials: [
            {
                id: 401,
                name: "Crushed Stone",
                testRequired: "Impact Value Test",
                unit: "cu.m",
                testsOnFile: 1,
                balance: 1,
                quantity: 200,
            },
            {
                id: 402,
                name: "Rock",
                testRequired: "Specific Gravity Test",
                unit: "cu.m",
                testsOnFile: 1,
                balance: 1,
                quantity: 150,
            },
            {
                id: 403,
                name: "Granite",
                testRequired: "Abrasion Test",
                unit: "cu.m",
                testsOnFile: 1,
                balance: 0,
                quantity: 100,
            },
            {
                id: 404,
                name: "Limestone",
                testRequired: "Water Absorption Test",
                unit: "cu.m",
                testsOnFile: 1,
                balance: 0,
                quantity: 50,
            },
        ],
        quantity: 500,
        unit: "cu.m",
        testsRequired: "Sieve Analysis",

        testsOnFile: 4,
        balance: 2,
    },
];
