name: lint-build

on: [push, pull_request]

jobs:
    lint-build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]

        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            DIRECT_URL: ${{ secrets.DIRECT_URL }}

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Lint project
              run: npm run check

            - name: Check format
              run: npm run format:check

            - name: Build project
              run: npm run build
