name: lint-test-build

on: [push, pull_request]

jobs:
    lint-test-build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x, 22.x]

        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            DIRECT_URL: ${{ secrets.DIRECT_URL }}
            NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install dependencies
              run: |
                  npm ci
                  npm install @rollup/rollup-linux-x64-gnu lightningcss-linux-x64-gnu @tailwindcss/oxide-linux-x64-gnu sass-embedded-linux-x64 --save-optional

            # ^ to fix weird ci error: "Cannot find module 'rollup'"

            - name: Lint project
              run: npm run check

            - name: Check format
              run: npm run format:check

            - name: Test project
              run: npm run test

            - name: Build project
              run: npm run build
