name: UI Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22.x]
        container:
            image: mcr.microsoft.com/playwright:v1.50.1-noble
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Run storybook tests
              run: npm run test:sb
