name: E2E Tests

on:
    pull_request:
        branches: [main, develop]

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest

        env:
            DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
            DIRECT_URL: ${{ secrets.DIRECT_URL }}
            NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
            NEXT_PUBLIC_SITE_URL: ${{ secrets.STAGING_URL }}
            SKIP_ENV_VALIDATION: true
            TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
            TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Install dependencies
              run: npm ci

            - name: Install Playwright Browsers
              run: npx playwright install --with-deps

            - name: Run Playwright tests
              run: npm run test:e2e

              # upload the Playwright report
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
